import { useState } from 'react';
import { Card } from '../../components/Card';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

export const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: 'What is ToolBox?',
      answer: 'ToolBox is a collection of modern web development tools and utilities designed to enhance your productivity. It includes design tools, games, and various utilities to help developers and designers in their daily work.',
    },
    {
      question: 'Do I need to create an account?',
      answer: 'An account is required to access certain features like the Game and Design pages. You can create an account by clicking the Login button and entering any username (3+ characters) and password (6+ characters).',
    },
    {
      question: 'Are the tools free to use?',
      answer: 'Yes, all tools in ToolBox are completely free to use. There are no hidden fees or premium features. Our goal is to provide useful utilities to the developer community at no cost.',
    },
    {
      question: 'Can I use the generated CSS in my projects?',
      answer: 'Absolutely! All CSS code generated by our tools (Border Viewer, Box Shadow Generator, etc.) can be freely used in your personal or commercial projects without any attribution required.',
    },
    {
      question: 'How do I copy the generated code?',
      answer: 'Each tool that generates code includes a copy button. Simply click the copy button to automatically copy the code to your clipboard, then paste it into your project.',
    },
    {
      question: 'Is my data stored on your servers?',
      answer: 'No, all data is stored locally in your browser using localStorage. We do not collect or store any personal information or project data on our servers. Your privacy is important to us.',
    },
    {
      question: 'What browsers are supported?',
      answer: 'ToolBox works on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version of your preferred browser for the best experience.',
    },
    {
      question: 'Can I contribute to the project?',
      answer: 'Yes! ToolBox is open to contributions. If you have ideas for new tools or improvements, feel free to reach out through our contact channels.',
    },
    {
      question: 'How often are new tools added?',
      answer: 'We regularly update ToolBox with new tools and features based on user feedback and demand. Check back frequently to discover new utilities.',
    },
    {
      question: 'What if I encounter a bug?',
      answer: 'If you find a bug or issue, please report it through our contact channels. We appreciate user feedback and work quickly to resolve any problems.',
    },
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-12">
        <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-full mb-4">
          <HelpCircle className="w-8 h-8 text-white" />
        </div>
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Frequently Asked Questions</h1>
        <p className="text-lg text-gray-600">Find answers to common questions about ToolBox</p>
      </div>

      <Card>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-gray-200 rounded-lg overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-4 text-left bg-white hover:bg-gray-50 transition-colors flex items-center justify-between"
              >
                <span className="font-medium text-gray-900">{faq.question}</span>
                {openIndex === index ? (
                  <ChevronUp className="w-5 h-5 text-gray-500 flex-shrink-0 ml-4" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-gray-500 flex-shrink-0 ml-4" />
                )}
              </button>
              {openIndex === index && (
                <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                  <p className="text-gray-700 leading-relaxed">{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </Card>

      <div className="mt-12 text-center">
        <Card>
          <div className="py-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-2">Still have questions?</h2>
            <p className="text-gray-600 mb-4">
              Can't find the answer you're looking for? Please reach out to our support team.
            </p>
            <Button>Contact Support</Button>
          </div>
        </Card>
      </div>
    </div>
  );
};
